# Generated by Django 4.0.3 on 2022-06-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.ForeignKey(blank=True, db_column='fld_user_level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.tbluserlevel'),
        ),
    ]
