# Generated by Django 4.0.3 on 2022-06-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblusersites',
            name='assigned_date',
            field=models.DateField(blank=True, db_column='fld_assigned_date', null=True),
        ),
    ]
