# Generated by Django 4.0.3 on 2022-06-10 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblUserFirebase',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('firebase_id', models.CharField(blank=True, db_column='fld_firebase_id', default='NA', max_length=255, null=True)),
                ('is_send_push', models.BooleanField(db_column='fld_is_send_push', default=True)),
                ('device_info', models.TextField(db_column='fld_device_info', default='NA')),
                ('is_active', models.BooleanField(db_column='fld_is_active', default=True)),
                ('is_delete', models.BooleanField(db_column='fld_is_delete', default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_column='fld_created_datetime')),
                ('user_id', models.ForeignKey(blank=True, db_column='fld_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_user_firebase',
                'managed': True,
            },
        ),
    ]
