# Generated by Django 4.0.3 on 2022-06-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblNotificationConfig',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('notification_type', models.CharField(blank=True, choices=[('check_in', 'check_in'), ('offline', 'offline'), ('check_out', 'check_out')], db_column='fld_notification_type', max_length=9, null=True)),
                ('notification_title', models.CharField(blank=True, db_column='fld_notification_title', default='NA', max_length=255, null=True)),
                ('notification_body', models.CharField(blank=True, db_column='fld_notification_body', default='NA', max_length=500, null=True)),
                ('notification_icon', models.CharField(blank=True, db_column='fld_notification_icon', default='NA', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='fld_is_active', default=True)),
                ('is_delete', models.BooleanField(db_column='fld_is_delete', default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_column='fld_created_datetime')),
            ],
            options={
                'db_table': 'tbl_notification_config',
                'managed': True,
            },
        ),
    ]
