# Generated by Django 4.0.3 on 2022-06-10 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_tblnotificationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblnotificationconfig',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('check_in', 'check_in'), ('offline', 'offline'), ('check_out', 'check_out')], db_column='fld_notification_type', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TblPushNotificationLog',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('firebase_response', models.TextField(blank=True, db_column='fld_firebase_response', default='NA', null=True)),
                ('status_code', models.CharField(blank=True, db_column='fld_status_code', default='NA', max_length=10, null=True)),
                ('is_success', models.BooleanField(db_column='fld_is_success', default=True)),
                ('is_active', models.BooleanField(db_column='fld_is_active', default=True)),
                ('is_delete', models.BooleanField(db_column='fld_is_delete', default=False)),
                ('datetime', models.DateTimeField(db_column='fld_datetime')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, db_column='fld_created_datetime')),
                ('notification_type_id', models.ForeignKey(blank=True, db_column='fld_notification_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.tblnotificationconfig')),
                ('user_firebase', models.ForeignKey(blank=True, db_column='fld_user_firebase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.tbluserfirebase')),
                ('user_id', models.ForeignKey(blank=True, db_column='fld_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_push_notification_log',
                'managed': True,
            },
        ),
    ]
