# Generated by Django 4.0.3 on 2022-06-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_tblnotificationconfig_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblnotificationconfig',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('forgets to check-in', 'forgets to check-in'), ('offline', 'offline'), ('outside of geolocation bound', 'outside of geolocation bound'), ('disable tracking', 'disable tracking'), ('changes datetime', 'changes datetime')], db_column='fld_notification_type', max_length=100, null=True),
        ),
    ]
